name: flutter_app_template
description: A new template app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  template_package: ^2.0.2
  package_info: ^2.0.2
  flutter_launcher_icons: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
flutter_icons:
  android: "launcher_icon" #flutter pub run flutter_launcher_icons:main
  ios: true
  image_path: "assets/images/applogo.jpg"
  image_path_android: "assets/images/applogo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/locale/
    - assets/images/
    - assets/country_codes.json

